### ISSUE TITLE
Extension naming issue?

### ISSUE THREAD

**Issue by yermulnik** [wwsean08/gh-gh-status#6]
Hey, thanks for the great GH CLI extension, I managed to use as a primary tool it to see what's going on on GitHub when I suspect GitHub isn't healthy 👍🏻 
Though during an upgrade to latest version I found that GH CLI doesn't actually like extension's name as it trims `gh-` prefix from extension name (here's link to respective GH CLI function: https://github.com/cli/cli/blob/trunk/pkg/cmd/extension/command.go#L661-L666, which is called from within here: https://github.com/cli/cli/blob/trunk/pkg/cmd/extension/command.go#L392-L401).
Not sure there's something you can do about this though =(
The other way around probably would be to add upgrade instructions to README and mention this extension upgrade needs special handling from user end: either use its full name or upgrade it in a bulk along with all other extensions pending upgrade.

```shell
> gh extension upgrade --dry-run --all | fgrep gh-status
[gh-status]: would have upgraded from v0.1.3 to v0.2.0

> gh extension upgrade --dry-run gh-status
X Failed upgrading extension status: no extension matched "status"

> gh extension upgrade --dry-run wwsean08/gh-gh-status
[gh-status]: would have upgraded from v0.1.3 to v0.2.0
✓ Would have upgraded extension
```

**Comment by wwsean08** [comment]
ah good to know, I will update the readme documentation this weekend.

It looks like it would have worked with `gh-gh-status` which makes sense given the way it works.

```shell
> gh extension upgrade gh-gh-status                                                                                                                                                                                                                                                                                                                           ✔  3.0.0 
[gh-status]: already up to date
✓ Successfully upgraded extension
```

Thanks for letting me know :)

**Comment by yermulnik** [comment]
> It looks like it would have worked with `gh-gh-status` which makes sense given the way it works.

Yeah, yet another way to circumvent this 😄

**Comment by wwsean08** [comment]
I've updated the documentation in the readme as well as updated the command `--help` flag to provide the information about how to upgrade, so I'm going to close this out.  Thanks again for reporting this :) .

**Comment by yermulnik** [comment]
@wwsean08 Thanks!
